version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: trello_postgres
    environment:
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: trello_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trello_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: trello_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: trello@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trello_network

  backend:
    build:
      dockerfile: dockerfile
    container_name: trello_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://trello_frontend:80
      - PORT=3000
    networks:
      - trello_network

  frontend:
    build:
      context: ../FE-CDTN-Trello
      dockerfile: dockerfile
    container_name: trello_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - trello_network

volumes:
  postgres_data:

networks:
  trello_network:
    driver: bridge